# -*- coding: utf-8 -*-
"""Internal_ass_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tl0jX72OrUlVzYXYna24X_AW95pET-FZ
"""

# Lab 1
#1
length=float(input("Enter the length"))
breadth=float(input("Enter the breadth"))
area=length*breadth
print("Area: "+str(area)+" m sq")

#2
Height=float(input("Enter the height in m"))
Weight=float(input("Enter the weight in kg"))
BMI=Weight/(Height**2)
print(BMI)

# 3
n_students=int(input("Enter the number of students"))
store_lis=[]
for itr in range(n_students):
  stu_dict={
    "Name":input("Enter the name"),
    "Scores":input("Enter the scores")
  }
  store_lis.append(stu_dict)
print(store_lis)

#Lab 2
#4
age=int(input("enter the age"))
if age<18:
  print("Minor")
elif age>=18 and age<50:
  print("Adults")
else:
  print("Seniors")

#5
for itr in range(2,52,2):
  print(itr)



#6
import getpass
print("Enter the pass")
password=getpass.getpass()

#Lab 3
#7
import statistics as s
def avg_calc(num_lis):
  av_num=sum(num_lis)
  print(av_num/len(num_lis))

num_list=[1,2,3,5,6]
avg_calc(num_list)

#8
def check_vow(str_inp):
  ct=0
  for itr in str_inp:
    if itr =='a'or itr =='e'or itr =='i'or itr =='o'or itr =='u':
      ct+=1
  return ct

str_inp=str(input("Enter the string"))
coun=check_vow(str_inp)
print(coun)

#9
import datetime
print(datetime.datetime.now())

#Lab 4
#10
def addition(num1,num2):
  try:
    ans=num1+num2
    return ans
  except :
    return("enter int value only")
num1=int(input("Enter the num1"))
num2=int(input("Enter the num2"))
print(addition(num1,num2))

#11
int1=int(input("Enter the integer"))
try:
    if int1>0:
      print("Integer Ok")
except :
    print("Negative int")

#12
def Division(num1,num2):
  try:
    ans=num1/num2
    return num1/num2
  except ZeroDivisionError:
    return("Number cannot be divided by zero")
num1=int(input("Enter the num1"))
num2=int(input("Enter the num2"))
print(Division(num1,num2))

#Lab 5
#13
with open("/content/sample_data/Sangavi.txt",'w') as file_new:
  file_new.write("Hello Python")
file_new.close()
print("File writtem successfully")

#14
read_file=open("/content/sample_data/Sangavi.txt",'r')
print(read_file.read())
read_file.close()

#15
with open("/content/sample_data/Sangavi.txt",'a') as file_new:
  new_str="Hai append"
  file_new.write(f"\n{new_str}")
file_new.close()
print("File appended successfully")